server:
  port: 8081

spring:
  cloud:
    discovery:
      enabled: true
## OR
#eureka:
#  client:
#    register-with-eureka: true

  application:
    name: produits-service
  datasource:
    url: jdbc:h2:mem:testDB


#eureka configs
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
