server:
  port: 8888

spring:
  application:
    name: proxy-service

#eureka configs
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true




## spring actuator (proxy)
## access to http://localhost:8888/actuator/routes

#management:
#  endpoint:
#    routes:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
